version: '3'
services:
  proxy:
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Astro HTTP Redirect Port
      - '443:443' # Astro HTTPS Port
      - '8080:8080' # Deno API Port
    volumes:
      - ./proxy/conf:/etc/nginx/conf.d
      - ./proxy/ssl:/etc/ssl/private
  astro:
    build:
      context: .
      dockerfile: astro-src/Dockerfile
    hostname: "re-astro"
  surreal:
    build:
      context: .
      dockerfile: surreal-src/Dockerfile
    hostname: "re-surreal"
  deno:
    build:
      context: .
      dockerfile: deno-src/Dockerfile
    hostname: "re-deno"
