version: '3'
services:
  proxy:
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Astro HTTP Redirect Port
      - '443:443' # Astro HTTPS Port
      - '8080:8080' # Deno
      #- '8000:8000' # SurrealDB
    volumes:
      - ./proxy/conf:/etc/nginx/conf.d
      - ./proxy/ssl:/etc/ssl/private
  astro:
    restart: unless-stopped
    build:
      context: .
      dockerfile: astro-src/Dockerfile
    hostname: "astro"
  surreal:
    restart: unless-stopped
    build:
      context: .
      dockerfile: surreal-src/Dockerfile
    hostname: "surreal"
  deno:
    build:
      context: .
      dockerfile: deno-src/Dockerfile
    hostname: "deno"
