version: '3'
services:
  re-astro:
    build:
      context: .
      dockerfile: astro-src/Dockerfile
    ports:
      - "127.0.0.1:8080:8085"
    hostname: "re-astro"
  re-surreal:
    build:
      context: .
      dockerfile: surreal-src/Dockerfile
    hostname: "re-surreal"
